### ISSUE TITLE
--exec-on-unmount reports wrong mount point and volume for multi partition disks

### ISSUE THREAD

**Issue by DBMandrake** [IgnorantGuru/udevil#61] opened 2015-10-16 14:08 UTC
I've been doing some initial testing on the --exec-on options and have discovered a possible issue with drives containing more than one partition. It seems that --exec-on-unmount incorrectly reports the same partition's mount point and volume name when unmounting each individual partition.

My test case is a hard drive with 5 partitions with 5 different file systems which I use for automounter testing - exfat, fat32, HFS, Ext4 and NTFS, with a Volume name reflecting the file system type.

When the drive is connected, --exec-on-drive "script %f %d %l" gives me:

`/dev/sda2 /media/EXFAT EXFAT`
`/dev/sda1 /media/FAT32 FAT32`
`/dev/sda5 /media/HFS HFS`
`/dev/sda6 /media/Ext4 Ext4`
`/dev/sda3 /media/NTFS NTFS`

Which is as expected, however when manually unmounting the partitions one by one --exec-on-unmount "script %f %d %l" gives me:

`/dev/sda2 /media/NTFS NTFS`
`/dev/sda6 /media/NTFS NTFS`
`/dev/sda1 /media/NTFS NTFS`
`/dev/sda5 /media/NTFS NTFS`
`/dev/sda3 /media/NTFS NTFS`

Eg the device node is correct, however the mount point and Volume name are both wrong. Which partitions mount point and volume name is used seems to change - possibly it depends on the order in which I unmount them.

**Comment by IgnorantGuru** [comment] 2015-10-16 14:23
Thanks for your report.  This sounds like a duplicate of #56, which should already be fixed in udevil 0.4.4 (devmon 1.1.8).

**Comment by DBMandrake** [comment] 2015-10-16 14:46
Sorry for the duplicate - we are using the Debian Jessie version of udevil which is udevil 0.4.3-1 and devmon 1.1.7.

**Closed as completed** 2015-10-16 15:08 UTC
Labels: duplicate
